=== ageru666/lab7_DC/src/news_agency_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="news_agency" type="NewsAgencyType"/>

    <xs:complexType name="NewsAgencyType">
        <xs:sequence>
            <xs:element name="news_categories" type="NewsCategoriesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="NewsCategoriesType">
        <xs:sequence>
            <xs:element name="category" type="CategoryType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CategoryType">
        <xs:sequence>
            <xs:element name="news" type="NewsType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="NewsType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:integer" use="required"/>
                <xs:attribute name="title" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== ageru666/lab7_DC/src/news_agency.xml
<?xml version="1.0" encoding="UTF-8"?>
<news_agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="news_agency_schema.xsd"
             xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <news_categories>
        <category id="1" name=")">
            <news id="101" title="News Title 1">News Text 1</news>
            <news id="102" title="News Title 2">News Text 2</news>
        </category>
        <category id="2" name="Economy">
            <news id="201" title="News Title 3">News Text 3</news>
            <news id="202" title="News Title 4">News Text 4</news>
        </category>
        <category id="3" name="Technology">
            <news id="301" title="News Title 5">News Text 5</news>
            <news id="302" title="News Title 6">News Text 6</news>
        </category>
    </news_categories>
</news_agency>
